---
- name: restart crond
  systemd:
    name: crond.service
    state: restarted
  listen: timezone changed

- name: restart sshd 
  systemd:
    name: sshd.service
    state: restarted
  listen: sshd_config changed

