<?php

/**
 * @file
 * Contains gobear_jobs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gobear_jobs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the xttd_helper module.
    case 'help.page.gobear_jobs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gobear jobs page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function gobear_jobs_theme() {
  return [
    'gobear_jobs' => [
      'render element' => 'children',
    ],
  ];
}

