  <?php

/**
 * @file
 * Contains gobear_jobs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_help().
 */
function gobear_jobs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gobear_jobs module.
    case 'help.page.gobear_jobs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Go bear jobs') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function gobear_jobs_theme() {
  return [
    'gobear_jobs' => [
      'variables' => array('jobs_var' => NULL),
    ],
  ];
}



function gobear_jobs_webform_submission_presave(WebformSubmissionInterface $webform_submission){
    global $base_url;
    $age = $_GET['age'];
    $city = $_GET['city'];

    //var_dump($webform_submission);
    $webform_submission->setElementData('age', $age);
    $webform_submission->setElementData('city', $city);


  }
