---
- name: yum install httpd
  yum:
    state: present
    name:
      - httpd
      - httpd-devel
      - mod_ssl
  notify: restart httpd

- name: create /etc/systemd/system/httpd.service
  template:
    src: httpd.service.j2
    dest: /etc/systemd/system/httpd.service
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: 
    - reload systemd
    - restart httpd

- name: copy /etc/httpd/conf/httpd.conf
  template:
    src: "{{ apache_conf_template }}" # defaults/main.yml
    dest: /etc/httpd/conf/httpd.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: restart httpd

- name: mkdir /etc/httpd/conf.vhosts.d for application configuration
  file:
    path: /etc/httpd/conf.vhosts.d
    state: directory
    owner: root
    group: root
    mode: 0755

#- name: Attempt to change ownership on directory
#  file:
#    path: "/home/httpd/app_01/web"
#    state: directory
#    recurse: yes
#    owner: "apache"
#    group: "apache"
